export const actions = {
  CREATE_BOOK: 'CREATE_BOOK',
  CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',

  DELETE_BOOKS: 'DELETE_BOOKS',
  DELETE_BOOKS_SUCCESS: 'DELETE_BOOKS_SUCCESS',

  UPDATE_BOOK: 'UPDATE_BOOK',
  UPDATE_BOOK_SUCCESS: 'UPDATE_BOOK_SUCCESS',

  GET_BOOKS: 'GET_BOOKS',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
}
